### ISSUE TITLE
sort files function

### ISSUE THREAD

**Issue by drewgash** [PratikRamdasi/Computer_Vision#1]
Hi Pratik,
Please explain what the line`for file in sorted(glob.glob(path)):` is supposed to achieve because passing a **path** value e.g. TrainingNew/boxing/person01_boxing_d1_uncomp.avi/*.*  returns no value for **file**

Please bear with me :)

**Comment by drewgash** [comment]
The error:

```
Traceback (most recent call last):
  File "C:\Users\drewgash\Downloads\Computer-Vision-master\06_Human_Activity_Recognition\HOGFile.py", line 159, in <module>
    h= HOGCompute()
  File "C:\Users\drewgash\Downloads\Computer-Vision-master\06_Human_Activity_Recognition\HOGFile.py", line 121, in __init__
    clf.fit(TrainingData,Labels)
  File "C:\Python27\lib\site-packages\sklearn\svm\base.py", line 149, in fit
    X, y = check_X_y(X, y, dtype=np.float64, order='C', accept_sparse='csr')
  File "C:\Python27\lib\site-packages\sklearn\utils\validation.py", line 573, in check_X_y
    ensure_min_features, warn_on_dtype, estimator)
  File "C:\Python27\lib\site-packages\sklearn\utils\validation.py", line 470, in check_array
    context))
ValueError: Found array with 0 feature(s) (shape=(299, 0)) while a minimum of 1 is required.
```

**Comment by PratikRamdasi** [comment]
Hi Andrew,
I had used a specific naming format to save the frames extracted from the video. You may continue without using "sort_files" function. Just extract the frames into separate folder and continue with feature extraction. 

Thank you for pointing that out. It was an old code and I plan to update this soon.

**Comment by drewgash** [comment]
Hi Pratik,
I came up with a frame extraction script that works for me. Since we're dealing with a large number of videos from KTH, how best can I organize the frames? Do you have a directory structure I could use?
Feature extraction is executed in HOGTest.py 



    On Thursday, August 9, 2018, 3:26:55 AM GMT+3, Pratik M Ramdasi <notifications@github.com> wrote:  
 
 
Hi Andrew,
I had used a specific naming format to save the frames extracted from the video. You may continue without using "sort_files" function. Just extract the frames into separate folder and continue with feature extraction.

Thank you for pointing that out. It was an old code and I plan to update this soon.

**Comment by PratikRamdasi** [comment]
Hi Andrew,
Unfortunately I do not have  directory structure as of now (it was in my old system). You can try without saving the frames separately and performing feature extraction in run time. I believe I had used a subset of videos per category and not all of them as there are many.

Thanks.
Pratik Ramdasi

**Comment by drewgash** [comment]
Noted with thanks Pratik. Another question kindly, how do I finally go about testing for the different human activities on a sample video?

**Comment by drewgash** [comment]
Noted with thanks Pratik. Another question kindly, how do I finally go about testing for the different human activities on a sample video?

    On Sunday, August 12, 2018, 9:03:35 PM GMT+3, Pratik M Ramdasi <notifications@github.com> wrote:  
 
 
Hi Andrew,
Unfortunately I do not have directory structure as of now (it was in my old system). You can try without saving the frames separately and performing feature extraction in run time. I believe I had used a subset of videos per category and not all of them as there are many.

Thanks.
Pratik Ramdasi

**Comment by PratikRamdasi** [comment]
You can continue testing in a similar way to training.
1. store test videos (per catagory)
2. loop over each one -> frame extraction -> feature extraction
3. provide feature vector to ALREADY FITTED SVM MODEL (check training file) and get the predicted label.

Please refer to HOGtest.py for more details. Hope this helps.

Thanks,
Pratik Ramdasi

**Comment by drewgash** [comment]
I was referring to putting this to work in runtime. That's still the way?
    On Tuesday, August 14, 2018, 9:00:34 PM GMT+3, Pratik M Ramdasi <notifications@github.com> wrote:  
 
 
You can continue testing in a similar way to training.
   
   - store test videos (per catagory)
   - loop over each one -> frame extraction -> feature extraction
   - provide feature vector to ALREADY FITTED SVM MODEL (check training file) and get the predicted label.

Please refer to HOGtest.py for more details. Hope this helps.

Thanks,
Pratik Ramdasi

**Comment by PratikRamdasi** [comment]
Oh, that might be little bit difficult with the same procedure. You might want to check some online resources for more sophisticated methods. If you have time constraint, I will probably suggest current strategy of storing features (without the sort function) and testing. 

If interested, Deep Learning based method:
https://github.com/jindongwang/Deep-learning-activity-recognition

Pratik Ramdasi

**Comment by drewgash** [comment]
I thought it would lead to this kind of real world application? OpenCV Action Recognition Software 

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
OpenCV Action Recognition Software

This is the unfinished version of my action recognition program. Unfortunately, the latest version and many othe...
 |

 |

 |

**Comment by drewgash** [comment]
I thought it would lead to this kind of real world application? https://www.youtube.com/watch?v=JlqrlrpE2O4



    On Tuesday, August 14, 2018, 10:31:39 PM GMT+3, Pratik M Ramdasi <notifications@github.com> wrote:  
 
 
Oh, that might be little bit difficult with the same procedure. You might want to check some online resources for more sophisticated methods. If you have time constraint, I will probably suggest current strategy of storing features (without the sort function) and testing.

If interested, Deep Learning based method:
https://github.com/jindongwang/Deep-learning-activity-recognition

Pratik Ramdasi

**Comment by PratikRamdasi** [comment]
Yes, it should. For details about this application, you can check out author's github page menitioned in the description of the video.

**Comment by drewgash** [comment]
It's very incomplete. I'll keep digging for solutions.
    On Wednesday, August 15, 2018, 7:22:00 PM GMT+3, Pratik M Ramdasi <notifications@github.com> wrote:  
 
 
Yes, it should. For details about this application, you can check out author's github page menitioned in the description of the video.

**Comment by PratikRamdasi** [comment]
Cool. I Hope this was helpful for you. Good luck for your project. Please feel free to reach out for any suggestions/help.

Thanks.

**Comment by drewgash** [comment]
Sure thing Pratik.

Sent from Yahoo Mail on Android 
 
  On Wed, 15 Aug 2018 at 20:06, Pratik M Ramdasi<notifications@github.com> wrote:   
Cool. I Hope this was helpful for you. Good luck for your project. Please feel free to reach out for any suggestions/help.

Thanks.
