### ISSUE TITLE
folder and files missing

### ISSUE THREAD

**Issue by MohitMourya** [PratikRamdasi/Computer_Vision#2]
TrainingNew/
Test/
.pkl files are not in the repo.

can you please explain how to use this code?

**Comment by PratikRamdasi** [comment]
@MohitMourya This is an older script and I haven't uploaded the mentioned files, apologies for that. 
To give a brief idea:
1. `TrainingNew` and `Test` folder contains videos collected from the dataset/s mentioned in description `Readme.txt` (each video is around ~4s duration with ~25 fps, more information here http://www.nada.kth.se/cvap/actions/ ). 
2. `HOGFile.py` -> Frames were extracted from Training videos into separate folders, trained HOGPH feature based SVM classifier, saved model `.pkl` file. 
3. `HOGTest.py` -> Frames extracted from Test videos, predictions using SVM model per video

Please check the code functions for more details. Hope this was helpful. Please let know if you have any other issues understanding the scripts.
